---
- name: Install chezmoi
  pacman:
    name: chezmoi
    state: present
  become: yes

- name: Install dotfiles
  command: chezmoi init Hiroya-W/dotfiles
  changed_when: False

- name: Pull dotfiles
  command: chezmoi git pull
  changed_when: False

- name: Check changes in dotfiles
  command: chezmoi diff
  register: result
  changed_when: False

- name: Apply user dotfiles
  command: chezmoi apply --force
  when: result.stdout | length > 0

- name: Reload i3wm
  command: i3msg reload
  when: result.stdout | length > 0
