---
- name: Install rcm
  pacman:
    executable: yay
    name: rcm
    state: present
  become: yes
  become_user: "{{ aur_builder_user }}"
  when: dotfiles is defined

- name: Clone user dotfiles
  git:
    repo: "{{ dotfiles.url }}"
    dest: /home/{{ ansible_env.USER }}/{{ dotfiles.destination }}
    accept_hostkey: yes
    update: no
  when: dotfiles is defined

- name: Install user dotfiles
  command: env RCRC=/home/{{ ansible_env.USER }}/{{ dotfiles.destination }}/rcrc rcup
  when: dotfiles is defined
