---
- name: Install chezmoi
  pacman:
    name: chezmoi
    state: present
  become: yes
  when: dotfiles is defined

- name: Clone user dotfiles
  git:
    repo: "{{ dotfiles.url }}"
    dest: /home/{{ ansible_env.USER }}/{{ dotfiles.destination }}
    update: no
  when: dotfiles is defined

- name: Install user dotfiles
  command: chezmoi apply --force
  when: dotfiles is defined
