---
- name: Install bluetooth libraries
  pacman:
    name:
      - bluez
      - bluez-libs
      - bluez-utils
      - pulseaudio-bluetooth
    state: present
  become: yes

- name: Install frontend to control bluetooth
  pacman:
    name: blueman
    state: present
  become: yes

- name: Unblock the bluetooth service
  service:
    name: rfkill-block@bluetooth.service
    enabled: no
    state: stopped

- name: Enable and start the bluetooth service
  service:
    name: bluetooth.service
    enabled: yes
    state: started
