---
- name: Install polybar
  kewlfft.aur.aur:
    use: yay
    name: polybar
    state: present
  become: yes
  become_user: "{{ aur_builder_user }}"

- name: Install polybar-adapta-theme fonts
  pacman:
    name:
      - ttf-iosevka-nerd
      - ttf-fantasque-sans-mono
    state: present
  become: yes
