---
- name: Install docker and docker-compose
  pacman:
    name:
      - docker
      - docker-compose
    state: present
  become: yes

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: started
    enabled: yes
  become: yes

- import_tasks: docker_users.yml
  when: docker_users | length > 0
