---
- name: Enable system clock synchronized
  command: timedatectl set-ntp true
  when: ntp_system_clock_sync == True
  become: yes

- name: Disable system clock synchronized
  command: timedatectl set-ntp false
  when: ntp_system_clock_sync == False
  become: yes

- name: Change pacman mirror
  command: pacman-mirrors --geoip
  become: yes

- name: Refresh pacman mirrors
  pacman:
    update_cache: yes
  become: yes

- import_tasks: user.yml
