---
- name: Copy pacman configuration file
  copy:
    src: pacman.conf
    dest: /etc/pacman.conf
  become: yes

- name: Change pacman mirror
  command: pacman-mirrors --geoip
  become: yes

- name: Refresh pacman mirrors
  pacman:
    update_cache: yes
  become: yes
