---
- name: Uninstall pulseaudio
  pacman:
    name: 
      - pulseaudio
      - pulseaudio-bluetooth
    state: absent
    force: yes
  become: yes

- name: Install pipewire
  pacman:
    name:
      - pipewire
      - wireplumber
      - pipewire-pulse
    state: present
  become: yes

- name: Install frontend for pulseaudio
  pacman:
    name: pavucontrol
    state: present
  become: yes

- name: Start PulseAudio client
  systemd:
    name: pipewire-pulse
    state: started
    scope: user

- name: Install NoiseTorch
  pacman:
    executable: yay
    name: noisetorch
    state: present
  become: yes
  become_user: "{{ aur_builder_user }}"
