---
- name: Install lxappearance
  pacman:
    name: lxappearance
    state: present
  become: yes

- name: Install adapta gtk theme / papirus icon theme
  pacman:
    name:
      - adapta-gtk-theme
      - papirus-icon-theme
      - papirus-maia-icon-theme
    state: present
  become: yes

- include_tasks: tokyonight.yml
