---
- name: Uninstall i3lock
  pacman:
    name: i3lock
    state: absent
    force: yes
  become: yes

- name: Install i3lock-color
  pacman:
    executable: yay
    name: i3lock-color
    state: present
  become: yes
  become_user: "{{ aur_builder_user }}"

- name: Install betterlockscreen
  pacman:
    executable: yay
    name: betterlockscreen
    state: present
  become: yes
  become_user: "{{ aur_builder_user }}"
