---
- name: Install fontpreview
  pacman:
    executable: yay
    name: fontpreview
    state: present
  become: yes
  become_user: "{{ aur_builder_user }}"
  when: install_fontpreview | bool

- name: Install fonts
  pacman:
    name:
      - noto-fonts
      - noto-fonts-cjk
      - noto-fonts-emoji
      # adapta-nokto theme for polybar
      - ttf-iosevka-nerd
      - ttf-fantasque-sans-mono
    state: present
  become: yes

- name: Install AUR fonts
  pacman:
    executable: yay
    name: ttf-hackgen
    state: present
  become: yes
  become_user: "{{ aur_builder_user }}"
