---
- name: Install fonts
  pacman:
    name:
      - noto-fonts-emoji
    state: present
  become: yes

- name: Install AUR fonts
  pacman:
    executable: yay
    name: ttf-hackgen
    state: present
  become: yes
  become_user: "{{ aur_builder_user }}"
